spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student_management
    username: root
    password: root
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: javamailsender2024@gmail.com
    password: uiiz kuxy pcfo zmfp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
picture:
  upload:
    directory: C:\\Users\\xXx\\IdeaProjects\\spring\\StudentManagement\\pictures